name: common-cluster-v1

cluster_settings:
  name: containerInsights
  value: enabled

fargate_capacity_providers:
  FARGATE:
    default_capacity_provider_strategy:
      weight: 50
  FARGATE_SPOT:
    default_capacity_provider_strategy:
      weight: 50
